name: demo_apis
services:
  products_api:
    container_name: products_api
    image: node:18
    volumes:
      - "$PWD:/app"
    command: ["node", "/app/dist/index.js"]
    ports:
      - 80:8080
    environment:
      - PORT=8080
    networks:
      default:
        ipv4_address: 172.18.0.2

networks:
  default:
    external: true
    name: teamwork